### PR TITLE
Fix NullPointerException

### PR DESCRIPTION
**Pull request by SiXuManYan**
Fix NullPointerException https://github.com/lipangit/JiaoZiVideoPlayer/issues/1681

### CODE REVIEW

**Comment by SiXuManYan** [comment]
```java
  @Override
            public void onChildViewDetachedFromWindow(View view) {
                JZVideoPlayer jzvd = view.findViewById(R.id.videoplayer);
                if (jzvd != null && JZUtils.dataSourceObjectsContainsUri(jzvd.dataSourceObjects, JZMediaManager.getCurrentDataSource())) {
                    if (JZVideoPlayerManager.getCurrentJzvd().currentScreen != JZVideoPlayer.SCREEN_WINDOW_FULLSCREEN) {
                        JZVideoPlayer.releaseAllVideos();
                    }
                }
            }
        });
```
中的
```java
JZVideoPlayerManager.getCurrentJzvd().currentScreen 改成 jzvd.currentScreen
```

**Comment by LightProspect** [comment]
if (jzvd != null && JZUtils.dataSourceObjectsContainsUri(jzvd.dataSourceObjects, JZMediaManager.getCurrentDataSource())) {我的程序在这一行就停止运行了 不在继续往下走了

**Comment by lipangit** [comment]
log 是啥

**Comment by lipangit** [comment]
你好，咱们项目推出数字通证饺子token，https://github.com/lipangit/JZT， 给所有提交过pr的朋友30000个JZT，表示对你过去对项目支持的感谢。
请下载币威钱包https://www.bitcv.app/，把里面的以太坊地址给我，币威的地址站内转账不需要手续费。这东西值不值钱不重要，玩的是信仰。
Hello, let's launch the JiaoZiToken, https://github.com/lipangit/JZT, and give all the friends who submitted pr 30,000 JZT, thank you for your support of the project.
Please download the coin wallet https://www.bitcv.app/?from=bitcvCom and give me the address of the Ethereum. There is no charge for transferring money at the address station. It is not important that the value of this thing is worthless. It is faith.

**Comment by lipangit** [comment]
你好，咱们项目推出数字通证饺子token，https://github.com/lipangit/JZT， 给所有提交过pr的朋友30000个JZT，表示对你过去对项目支持的感谢。
请下载币威钱包https://www.bitcv.app/，把里面的以太坊地址给我，币威的地址站内转账不需要手续费。这东西值不值钱不重要，玩的是信仰。
Hello, let's launch the JiaoZiToken, https://github.com/lipangit/JZT, and give all the friends who submitted pr 30,000 JZT, thank you for your support of the project.
Please download the coin wallet https://www.bitcv.app/?from=bitcvCom and give me the address of the Ethereum. There is no charge for transferring money at the address station. It is not important that the value of this thing is worthless. It is faith.

**Pull request closed without merging**
