### PR TITLE
Hotfix/readme update

### PR DESCRIPTION
**Pull request by qymspace**
Minor edits on README.md to fix grammatical errors and make it more readable.

### CODE REVIEW

**Comment by lipangit** [comment]
Thank you very much, I will pick useful things to current branch, 
This branch is to old, many conflicts . you should pull before commit.

**Comment by lipangit** [comment]
Thank you

**Comment by qymspace** [comment]
Yes, I pull from the branch about a month ago, seems you've made some changes since then.

**Comment by lipangit** [comment]
你好，咱们项目推出数字通证饺子token，https://github.com/lipangit/JZT， 给所有提交过pr的朋友30000个JZT，表示对你过去对项目支持的感谢。
请下载币威钱包https://www.bitcv.app/，把里面的以太坊地址给我，币威的地址站内转账不需要手续费。这东西值不值钱不重要，玩的是信仰。
Hello, let's launch the JiaoZiToken, https://github.com/lipangit/JZT, and give all the friends who submitted pr 30,000 JZT, thank you for your support of the project.
Please download the coin wallet https://www.bitcv.app/?from=bitcvCom and give me the address of the Ethereum. There is no charge for transferring money at the address station. It is not important that the value of this thing is worthless. It is faith.

**Pull request closed without merging**
