### PR TITLE
Add exoplayer to media interface 

### PR DESCRIPTION
**Pull request by kimnamcham**
Add exoplayer to media interface. Add set context method in class JZUtils and JZVideoPlayerStandard

### CODE REVIEW

**Comment by lipangit** [comment]
Great
JZVideoPlayerManager.getCurrentJzvd().getContext() to get Context, and remove Util.getContext.
then I will merge the pr, 

Do you want btc xrp ht, I want give you some.

**Comment by kimnamcham** [comment]
Sorry, but what does btc xrp ht mean ?

**Comment by lipangit** [comment]
Bitcoin  Ripple

**Comment by lipangit** [comment]
I will fix it

**Comment by kimnamcham** [comment]
i'm glad to get it ! :D

**Comment by lipangit** [comment]
Give me a address.

**Comment by kimnamcham** [comment]
@lipangit - My address is : rDu5Tv7cDKh5kmr6NjnxKmyezweCT3gzU4

**Comment by lipangit** [comment]
bitcoin or xrp  whitch coin

**Comment by kimnamcham** [comment]
My address is XRP coin

**Comment by lipangit** [comment]
Trader, patiently wait for the deal

**Comment by lipangit** [comment]
My xrp are in aex.com but can not withdrawal in that website.

**Comment by lipangit** [comment]
give you 100 xrp Just wait

**Comment by kimnamcham** [comment]
Sorry i'm new bie of xrp, and this address "rDu5Tv7cDKh5kmr6NjnxKmyezweCT3gzU4" need 20xrp to use it. So i create a new host address, can you stop old address and trade to new my address: 366377532

**Comment by kimnamcham** [comment]
Sorry for this inconvenience !

**Comment by lipangit** [comment]
image

XRP提现必须填写Destination Tag备注信息，请放在收款地址后面，空格隔开，格式： Address 备注

what is this mean , destination tag is what

**Comment by kimnamcham** [comment]
This is my tag: 1287972011

**Comment by lipangit** [comment]
https://xrpcharts.ripple.com/#/graph/rDu5Tv7cDKh5kmr6NjnxKmyezweCT3gzU4%201287972011

**Comment by lipangit** [comment]
https://xrpcharts.ripple.com/#/transactions/F37B60BA61F7A1F574C6CDC7496F63CF4CC083BAD77DEA085621F24D26005376

**Comment by lipangit** [comment]
good night

**Comment by kimnamcham** [comment]
Thanks a lot! I received it

**Comment by felipetorres** [comment]
Does we have now support to Exoplayer? \o/

**Comment by lipangit** [comment]
yes @felipetorres

**Comment by lipangit** [comment]
你好，咱们项目推出数字通证饺子token，https://github.com/lipangit/JZT， 给所有提交过pr的朋友30000个JZT，表示对你过去对项目支持的感谢。
请下载币威钱包https://www.bitcv.app/，把里面的以太坊地址给我，币威的地址站内转账不需要手续费。这东西值不值钱不重要，玩的是信仰。
Hello, let's launch the JiaoZiToken, https://github.com/lipangit/JZT, and give all the friends who submitted pr 30,000 JZT, thank you for your support of the project.
Please download the coin wallet https://www.bitcv.app/?from=bitcvCom and give me the address of the Ethereum. There is no charge for transferring money at the address station. It is not important that the value of this thing is worthless. It is faith.

**Pull request merged**
